name: 'Pull Request Contains Jira Task Check'

on:
  pull_request:
    # Possible values: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.5.0
        with:
          title-regex: "(\\[BIG-[0-9]+\\]).+"
          on-failed-regex-fail-action: true
          on-failed-regex-request-changes: true
          on-failed-regex-create-review: true
          on-failed-regex-comment:
            "Failed regex: `%regex%`!"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
